### PR TITLE
Feature requests n.62

### PR DESCRIPTION
**Pull request by marcoM32**
Hi @fathzer, in this pull request you can find a first draft of the functionality 62, let me know if you have any ideas on how to improve it. 

Cattura

### CODE REVIEW

**Comment by fathzer** [comment]
Hi Marco,

Sorry for the delay. I spent a lot of time chasing a bug in table html export ... I finally found the bug was already there in previous Yapbam versions (even in csv format). The problem is the table models encode some fields in html in order to be able to display multiple-lines in a single JTable Cell (typically to show subtransactions). So, HTML exporter encodes the html twice, making spaces to be replaced by &nbsp;. I will fix it before releasing a new version.

Thanks for the proposal. Here are my remarks:
* There's a bug when you have multiple checkbooks in the same account, and some have less than 3 checks, then, an alert is raised (see enclosed picture). As we are not obliged to delete the empty checkbooks, I think it would be better to only raise an alert when the sum of checks remaining on an account is less than the limit.
* For that reason, I think the alert icon should not be displayed in the table near a particular checkbook (the alert under the checkbook table is perfect).
* In your proposal, the user should go to the "administration" tab, then, select "Account management", then select an account to have the alert. I think it would be better to guide him. I propose to display an alert icon at the right of the "Administration" tab, same in "Account management", and finally near the account name in the account list (and of course under the checkbooks table).
The same kind of thing is already done on the "bilancio storico" tab (see enclosed picture).
* You took a simple approach to set the check number limit (a constant). In my personal case, 3 checks is reasonable. But I known some of Yapbam users who are little companies or associations. For them, 3 is very few. So I was thinking of something configurable, like the "avviso se il saldo è inferiore a". If you agree, I will soon provide you with a new version of yapbam-commons with this information stored in the data.
This last point is not mandatory to have it to work on the previous points.

Please tell me if you agree with my remarks and feel free to expose your own point of view :-)

Best regards,
Jean-Marc
CheckBookAlert
.

**Comment by marcoM32** [comment]
Hello @fathzer, sorry if i answer you just now but i have been quite busy with work.
I agree with you, i will work to get this kind of user experience, if you have a way to update the common library I can proceed with the developments even if I don't understand how you want to warn the user about which specific booklet is about to expire.. deleting the information from the table the message will appear even without selection and the user will have to check by hand which booklet is raising the problem, or am I wrong?

**Comment by fathzer** [comment]
Hi @marcoM32,

I've just pushed a preview of yapbam-commons release in branch 1.9.0 of yabam-commons project based on my initial proposal (a global threshold).
The changes that you will need are:
- Account has now a getCheckNumberAlertThreshold() and getRemainingChecks() methods
- GlobalData has now a setCheckNumberAlertThreshold (Account account, int threshold) method. When this method is called and effectively changes the threshold, a AccountPropertyChangedEvent.CHECK_NUMBER_ALERT_THRESHOLD event is fired.

Nevertheless, after reading you, I don't have a clear opinion about what should trigger an alert.
I understand you think warning the user about which specific booklet is about to expire is useful. I do not really understand why. I don't see the specific actions (different than the one he would take with a global alert) the user will take when such an alert is raised. But my imagination has strong limitations ;-)
So, maybe, we both thresholds:
- A global one (like the one I proposed).
- A per checkbook one (managed per checkbook or per account, I don't known), like in your original proposal.
In any case, I think totally empty checkbooks should not generate alerts if other non-empty checkbooks exists (for me, an alert is really a problem, an old empty checkbook is not a problem if you have another one). Maybe an alert icon if number of checks is not 0 but less than the threshold ?
We also could let the user choose in the preferences if he prefers to have alerts on global number of checks or on a per checkbook basis, and if he wants alerts on empty checkbooks ... Really, I'm not sure what is better ...

Best regards,
Jean-Marc

**Comment by marcoM32** [comment]
Hi @fathzer,
once again thank you for your work, I checked the library and it seems to me that there is everything you need! In the next few days I will try to develop what this new feature is needed, however I will not be able to be very fast for various reasons of time, please excuse me in advance. To tell the truth, I also have a lot of confusion about what is best to do about this notice but we will surely find the right way to do it. As soon as I have something working to show you I would find my commit.

Thank you, we'll update in the next few days.

Greetings

**Comment by fathzer** [comment]
Thanks.
Yapbam stays a long time without feature improvement. It can wait ... and I have a lot of opportunities to occupy my leisure time ;-)
So, take your time :-)

**Comment by marcoM32** [comment]
Hello @fathzer, I've seen a lot of changes in the code, the next release will be full of news 😄

As for the implementation on alerts, I have developed an alternative to the solution that I proposed to you which includes alert icons that guide the user to report. The new development foresees a preference on the notice at the account level, for now I have not integrated a preference at the booklet level also because it seems really excessive ... I have worked a lot trying to implement things in the best way also based on the my knowledge of the program! Hope you don't have to go rewrite all my code again 😄

I am attaching below some screenshots of the proposed solution:

Cattura

Cattura

For the warning I had to integrate a new library, I know that in Yapbam the widgets have been made almost all custom and that there are few external dependencies but I leave you the decision to include your similar widget if it already exists or select a similar library to show the warning ([balloontip ](https://github.com/timmolderez/balloontip) is just my proposal).

Let me know what you think, also update me if I can already proceed with the Italian translations passing through Crowdin at least as regards the developments already concluded. 

I hope I did a good job,
Greetings

**Comment by marcoM32** [comment]
Hello @fathzer,
I have not received any news from you, did you receive my code?  if you haven't had time yet i understand i just want to make sure you don't miss the changes ...

**Comment by fathzer** [comment]
Hi Marco,
I'm so sorry! I totally missed your previous message (shame on me).
I will try to review your contribution during this week-end.
Best regards
Jean-Marc

**Comment by marcoM32** [comment]
Don't worry, I'm waiting for your review.

**Comment by fathzer** [comment]
Hi Marco,

I have reviewed your proposal.

Let's start with the good news:
- Having a button to set the alert preferences related to the checkbooks in the checkbooks panel is not what I expected ... but it's a very good idea, much better than having it in the "account edit" panel.
- This preference dialog is cool.
- Your code complies with my habits ;-)

As you know me well now, you will not be surprised; I have some remarks too ;-):
- The "up" button in the preference dialog seems to be grayed out. Moreover, maybe the down button could be grayed out when the threshold is 1.
strangeButtons
- It seems the alert is not properly set in some cases:
missingAlert
You can see there's an alert in the Checkbooks panel, but none in the "Administration" and "Account Management" tabs.  To reproduce this, change the language in the "File/Preferences" menu.
- I would prefer the alert in the "Administration" and "Account Management" tabs to contain a text to explain what the alerts are. Here is an example about balance history alerts:
alertExample
- You're right, I don't like including new libraries ;-) And I think in this case, we could have a clean interface without it. Here is my proposal:
Proposal
Sorry I didn't have time to finish it: Of course, the alert icon should be present in Administration and Accounts management tabs. The previous point (alerts listed in popup on the tab) is also missing.

Tell me if you agree ... or not. And feel free to ask for help if some things don't seem easy to implement.

Best regards,
Jean-Marc

**Comment by marcoM32** [comment]
Hi @fathzer, no problem we are here to create a good feature so any improvement is welcome ... as for point 1 and 2 I will try to look at it in the next few days while for point 3 I honestly don't think I understand a full your proposal, can you confirm that you would like to return to a notice in the table and a tooltip with the explanation for the alert in the "Accout management" and / or "Administration" screen? If I understand what you mean by point 3 I can carry on the change.

Best regards,
Marco

**Comment by fathzer** [comment]
Hi Marco,
You're right, "we are here to create a good feature" :-)
Here is a more complete example of what I have in mind:
proposal
The first idea is to remove the alert message from the "Checkbooks" table. With the alert icon in the table and the "number of check leaves remaining" column, I think there's no need to tell again the number of checks remaining.
The second is to add a generic alert message in the tooltips of the "Administration" and "account management" tabs. This will tell the user why there's an alert icon. This behavior is consistent with the one of the "balance history" alerts.
I hope my explanation makes things clearer ... Tell me if something remains confusing.
Best regards,
Jean-Marc

**Comment by marcoM32** [comment]
Hi Jean-Marc, I have developed the solution we told ourselves, can you take a look? I am not too satisfied with the fact that I repeat the same check many times but I have not found any other solution .. I leave any improvements to you.
As for the first report you made to me, it looks like a Look & Feel Nimbus bug and I don't think I can do much about it, if you try whit the others L&f it is not present.

Greetings

**Comment by fathzer** [comment]
Hi Marco,
I started working on it ... but, as usual, I'm pretty busy, and I haven't finished.
I hope to finish before next week-end.  Stay tuned ;-)
Best regards,
Jean-Marc

**Comment by marcoM32** [comment]
Hi @fathzer, 
don't worry, do it when you have time. Meanwhile, I still made a commit to delete an old class that is no longer needed with the new solution, check my last commit.

**Comment by fathzer** [comment]
Hi Marco,
I worked on your code integration, and reduced the code duplication  (I didn't merge your code with Git to proceed with care).
I still have work to do:
- I'm not very confortable with the choice between an alert on a "per account" or "per checkbook" basis. I think both are useful (depending if the account is shared by two or more persons). Finally, I think the best way is to let the user choose.
- Some code should be in yapbam-commons project, typically to compute if there's an alert or not.
I will work on it as soon as possible.
Best regards,
Jean-Marc

**Comment by marcoM32** [comment]
Hi Jean-Marc,
I've seen your changes, you did very well to review my implementation because it was not entirely convincing, but I was unable to visualize a better alternative perhaps because as you say some "common" code would work better if it's putted on the common library.
As for the decision on the specification, I let you decide, even if, in my opinion, what has already been done represents a good basic functionality that can then possibly be improved in the future by adding the option of overwriting the preferences expressed for the account, for one or more of the available booklets.
At this point I await for your changes to be complete and then I start to translate the definitive labels for this new feature.
As for the next release, have you already got an idea on the road map you want to follow, would you like to insert other features?

**Comment by fathzer** [comment]
Hi Marco,

The release is almost ready :-)

I've released a 1.9.0 version of yapbam-commons (with some methods moved from yapbam to this library), and adds french translations to yapbam project. If you can add Italian translations in Crowdin, I will release the new version of Yapbam this week.

The bad new: I finally leave the alert on a per checkbook basis. Here is the problem that makes me change my mind:  
Imagine you set the limit to 5 checks in a chekbook. The limit is reached on a checkbook, so, an alert is raised. Then, you get a new checkbook from your bank and enter it in Yapbam. Ok, but the alert will still be raised until your old checkbook until it will be deleted :-( The only solution I see is to mark the checkbook for ignoring the alerts ... it become complex. Maybe for a future release...

I haven't thought about the new features. I will try to have a look at the feature requests during next week.

Best regards,

Jean-Marc

**Comment by marcoM32** [comment]
Hi @fathzer,
I updated the translations thank you very much for your work, I await the release of the new package in the meantime I add an idea to notify users of the new position of the code, we could add a message in the notification area by adding the link to the project home on GitHub for asking other users to participate in the development. What do you think?

**Comment by fathzer** [comment]
Hi Marco,
I released our work (version 0.21.0). I had no time to review the feature requests, I will try to have a look this week-end.
I don't really look for more developers as it requires a lot of time to review/adapt the proposals, and free time is rare ;-)
Best regards,
Jean-Marc
PS : I close this PR as code was "manually" merged into master branch.

**Comment by fathzer** [comment]
Hi @marcoM32 ,

I added three issues to the project. One feature request and 2 bugs (unfortunately there's a annoying bug in the new release).

I will work tomorrow on the one I assigned to me. Any help/idea/comments/code are welcome for the others ;-)

Best regards,

Jean-Marc

PS : I also invited you to join the Yapbam team (I don't have any idea of what we can do with that. So ... let see).

**Pull request closed without merging**
